### ISSUE TITLE
sendRequest function always return false for all drivers

### ISSUE THREAD

**Issue by mshifo** [matthewbdaly/sms-client#10]
any request always return false for all drivers because there is if condition to check if status code = 201 while it returns 200
```
return $response->getStatusCode() == 201;

```
![screenshot from 2018-06-14 12-06-11](https://user-images.githubusercontent.com/15183005/41406911-1abfa602-6fce-11e8-8341-2ad0312338fd.png)

**Comment by matthewbdaly** [comment]
Ok, I probably won't get a chance to look at this till the weekend.

Should be a straightforward fix (should be OK to just change it to always return true for the HTTP drivers, since Guzzle will throw an exception for a 400 or 500), so if you feel comfortable doing so, feel free to submit a pull request for that. Otherwise I should be able to take a look this weekend.

**Comment by matthewbdaly** [comment]
Have implemented those changes and created a new release. Does that solve the issue for you?

**Comment by matthewbdaly** [comment]
Guzzle will throw an exception if there is an error status code, and that gets translated into the exceptions defined by the package. If any one API uses a non 400 or 500 status code to report an error, that would need to be caught, but that would be a terrible implementation on the part of the API provider.
