### ISSUE TITLE
Passing object instead of array

### ISSUE THREAD

**Issue by uikolas** [matthewbdaly/sms-client#8]
What about passing object instead of array in this place, like SMSMessage which holds from, to, number methods and etc?
https://github.com/matthewbdaly/sms-client/blob/master/src/Drivers/Nexmo.php#L102

[Little about that, passing arrays](http://bestpractices.thecodingmachine.com/php/design_beautiful_classes_and_methods.html#avoid-option-arrays-in-constructors)

And why return bollean, when you can return response?

**Comment by matthewbdaly** [comment]
I'm not returning an HTTP response because theoretically the client could support drivers that don't use HTTP. For instance, at some point I intend to add a mail driver to suppport mail-to-SMS gateways, and that would make the response inconsistent.

I might consider amending the constructor arguments though.
